# set base mirror
FROM osrf/ros:jazzy-desktop-full

ARG PROXY
ENV http_proxy=${PROXY} https_proxy=${PROXY}

# 设置 ROS 环境变量
RUN echo "source /opt/ros/jazzy/setup.bash" >> /root/.bashrc

# 设置colcon_cd
RUN echo "source /usr/share/colcon_cd/function/colcon_cd.sh" >> ~/.bashrc && \
    echo "export _colcon_cd_root=/opt/ros/jazzy/" >> ~/.bashrc

# 安装必要依赖
RUN apt install python3-colcon-common-extensions

# 重置代理配置
ENV http_proxy= https_proxy=