# set base mirror
FROM osrf/ros:jazzy-desktop-full

ARG PROXY
ENV http_proxy=${PROXY} https_proxy=${PROXY}

ARG ROS_DISTRO=jazzy

# 设置 ROS 环境变量
RUN echo "source /opt/ros/jazzy/setup.bash" >> /root/.bashrc

# 设置colcon_cd
RUN echo "source /usr/share/colcon_cd/function/colcon_cd.sh" >> ~/.bashrc && \
    echo "export _colcon_cd_root=/opt/ros/jazzy/" >> ~/.bashrc

# 配置gazebo
RUN apt update -y && \
    apt-get install ros-${ROS_DISTRO}-ros-gz -y && \
    apt-get install lsb-release wget gnupg -y && \
    wget https://packages.osrfoundation.org/gazebo.gpg -O /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null && \
    apt update -y && \
    apt-get install gz-harmonic -y

# 重置代理配置
ENV http_proxy= https_proxy=